server:
  port: 8082
spring:
  application:
    name: user-center
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/xc_user?serverTimezone=UTC
      username: root
      password: 1234
      type: com.alibaba.druid.pool.DruidDataSource
   #   数据源其他配置
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      #空闲连接检查时间间隔
      timeBetweenEvictionRunsMillis: 60000
      #空闲连接最小空闲时间
      minEvictableIdleTimeMillis: 30000
      #解决mysql8小时的问题
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
      host: 192.168.25.128
      port: 6379
      jedis:
        pool:
          max-active: 8
          min-idle: 2
      timeout: 5000 #连接超时的时间
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.itcast.auth.pojo
  mapper-locations: classpath:mapper/*.xml
#jwt密钥配置
encrypt:
  key-store:
    #私钥
    location: classpath:xc.keystore
    #密钥库的访问密码
    secret: xuecheng
    #密钥别名
    alias: xckey
    #密钥的访问密码
    password: xuecheng

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: user-center
    prefer-ip-address: true

auth:
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: localhost



